from __future__ import annotations

from typing import Protocol


class StreamProcessAdapter(Protocol):
    def start_capture(self) -> None: ...
    def stop_capture(self) -> None: ...
    def is_alive(self) -> bool: ...
    def wait_until_live(self, timeout_seconds: float) -> bool: ...
